language: node_js
node_js:
  - 10
  - 12
jobs:
  include:
    - stage: npm release
      node_js: 10
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: support@travellink.com.au
        skip_cleanup: true
        node: "10.0"
        api_key:
          secure: OXJTguln44ZaLgscPSb97SP7uXTrDD8OW4dZHEyHhVmg+jSYs74weGlp9HxgPPlbFOj9vnK2oNFBQIwY6yDSq4V0fxYFLnjN7mgRHK3ZaSpkgQt9/E4XzSdvcFWbbdq8+jDCGRLPE7D4fU6/Ao3kIpAXm6xBIFeS1BQuvNeIeQ1NKyeGc30532E1eGMLmnGXoqj6IT4V3DjVy/4vLoa+gzHLM31Kh7a28maJynpvxWXp9IcUjhMY01i2723eCVwqtFh01FC4urrNW7bgydQE6kg6kTeAOPCjWWArttMvOsnhfELNtIin3Y6dwBJ1GF0CExN7zKFmaGEsaI/1wzI7dOHQOdFtajIJ+Sgjw4AZnhQ8oXRwwMMxjD4M+5jAd+TJM9nRafd9uaHid27yN+77YyRN30FZn18QxtnmBTiv5jUgsH4FtjZE5RlUCkyLLlQJbqakKUZS9OIHNdXn4tX5Czum0Xj2fY38y1Juv2uNx2XIL/4oKqd67X2SB0gFgSRpBLjG3Fr3FB7cUDKljsCWCdu+0pDbBbflpDJS7K1aDz3G6DKZliSCm7XHIrb6NS43d7xW84dXUqvqOUiw5SOCAQR6L4O1y3YFrqPSeMYNhmAS1GarptrtjigHz8zINI5L8HmoKsh1BUUCa6u9sKvtASIqUcZt0M1NaRuRbQrsulo=
        on:
          all_branches: true
          tags: true
